### ISSUE TITLE
Make recommendation on whether to re-apply as SANDBOX or INCUBATION level

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#1]
We need to make a decision on what CNCF Project LEVEL we are going to re-apply at.

Chris Anascsyk has advised us that we can re-apply as either of these, but we MUST meet to criteria.

**Comment by edrob999** [comment]
Maintainers had a meeting today (3/28) and decided to apply as sandbox

**Comment by dave-brace** [comment]
The leadership and Maintainers team reviewed the Sandbox Level application form and the Incubation Level form.
Our recommendation is to apply as SANDBOX.
This has been socialized with the Maintainers, Approvers, Reviewers and all other project teams.
All team concur and are in agreement.
