### ISSUE TITLE
Disable old gitbooks docs website

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#10]

**Comment by avishnu** [comment]
It's been decided to defer, since it's important to maintain the old release documentation contents for at least a year.

**Comment by edrob999** [comment]
Deferring is not a good option. The Gitbooks site still looks "live", and people may link to it.

Whata commonly done is an end of life notice on each page (for say 3 months), then remove the docs

Maintainers: please make a decision on the best course of action

**Comment by avishnu** [comment]
Acknowledging the comment https://github.com/openebs/community/issues/10#issuecomment-2145360805
Figuring out the optimal way to do the above.

**Comment by edrob999** [comment]
Maintainers decided to archive Gitbook version of the Mayastor documentation.  
- Gitbook will be de-commissioned in 3 months - August 31.
- After 31 August, until end of year the site will 301 to openebs.io

**Comment by balaharish7** [comment]
This issue is addressed and documented in PR [#216](https://github.com/openebs/mayastor-docs/pull/216).
