### ISSUE TITLE
Remove BLOGS from .io website IA

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#12]
There are 129 BLOGS docs that exists in the website.

Source location is here: https://github.com/openebs/website/tree/main/website/src/blogs

We need to review every one for...
1. Age
2. relevance
3. usefulness
4. can it be recycled and used in the new site
5. Should we keep it and update it
6. Should it be deleted

Assuming that it will take a minim of 30 mins per doc to review and make a decision (this is reasonable IMHO).
- that's 3,900 mins = 65 hours of work effort

**Comment by avishnu** [comment]
Blogs have been disabled.
