### ISSUE TITLE
Revise OpenEBS project logo from away from Mule

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#14]
We need to make a decision on what happening with the new OpenEBS as a new project as we reapply for CNCF for SANBOX.

We need to mentally get beyond the mindset that its just the OLD project getting back into CNCF. I'm not convinced that this is how CNCF TOC will view it. I believe that they will review our application on the merits that its a NEW application. 
- Yes there is a complexities to our status and applications...
   - all of our IP and Trademarks and repo have already been transfer into CNCF ownership
   - so technically we are half-way in and half-way out of the door
   - But its unclear if we have any rights to to re-use anything as part of our application... which includes the project logo

**Comment by orville-wright** [comment]
@edrob999 and @orville-wright met with Jorge Castro to get advice & guidance on original project logo (i.e. The Mule). JorgeC advised the team to create a new project logo for the new Sandbox   re-join application. Designs are already being reviewed. 

The old original project logo (i.e. The Mule) will be assigned to the openebs-archive org.

**Comment by orville-wright** [comment]
As advised by Jorge Castro (CNCF Dev Relations)... we have the option of doing this. 
Although our Sandbox logo has been archived, we may get ownership transferred back to us when we successfully rejoin CNCF Sandbox. 
This is not guaranteed to happen (as per Jorge Castro guidance). 

The team met and has discussed this option in depth & decided to leave the current logo unchanged & apply as it (i.e. the Legacy Mule logo). 
We will consider updating it once we are at Sandbox level if we are granted ownership of the Legacy Mule logo. If not, we will design a replacement.

**Comment by avishnu** [comment]
Closing this issue as the corresponding project item is marked as done.
