### ISSUE TITLE
Validate helm chart for archived projects

### ISSUE THREAD

**Issue by edrob999** [openebs/community#17]

**Comment by avishnu** [comment]
The legacy repositories have been transferred to the openebs-archive GH org and installation instructions have been modified accordingly in the Helm chart index.md files.

It's been decided to do the following as well:
1. Amend the parent repo readme files in the openebs-archive org to represent this change
2. Update master org (openebs-archive) readme to represent this change
3. Amend the older documentation contents on openebs.io/docs to represent this change

**Comment by orville-wright** [comment]
After the initial rollout of the new Unified Helm installer for the parent openebs org, we realized that Helm was broken (we broke it with thee project structure) so we decided to unarchive 1 repo (charts) from the Archive org and migrate it back into the openebs parent org.

The main issue is that GH Pages (where our Helm chat is served from) cannot do **https 301 status** redirects like a regular web server can. This is an unrecoverable error state for Helm.
