### ISSUE TITLE
Revise consolidated Governance.md document

### ISSUE THREAD

**Issue by edrob999** [openebs/community#19]
Author a **NEW** [Governance doc](/openebs/community/GOVERNANCE.md) doc for the OpenEBS project that structures the governance system that the new Unified project **(5 unified repos)** will operate under.
- The current Governance structure was not designed for this new project structure
- Our objective to to achieve a higher quality and more vibrant community focus that meets the CNCF community standard and CNCF governance guidelines.
- We fell out of compliance with our old governance structure, due to the complexity of our project (i.e. too many repos and projects with different governance, contributing guidelines per repo/project). We have now fixed this issue with a **[SINGLE UNIFIED GOVERNANCE](/openebs/community/GOVERNANCE.md)** doc for all 5 repos in the Parent OpenEBS project org.

We believe that our new governance structure & system sets the project on a **better more balanced** governance operating mode.

**Comment by orville-wright** [comment]
- [x] New Governance doc has been authored by @edrob999 
- [x] @orville-wright has reviewed and updated it
- [x] @avishnu has reviewed and updated it
- [x] @tiagolobocastro has reviewed and updated it
- [ ] @niladrih has reviewed and updated it
- [x] @Abhinandan-Purkait has reviewed and updated it
- [x] Doc is live in [Community repo](/openebs/community)

**Comment by avishnu** [comment]
Closing this as reviews are completed.
