### ISSUE TITLE
Apply to relevel to SANDBOX or INCUBATION

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#2]
The CNCF Sandbox and Incubation application forms are live GitHub Webform.

Sandbox is here: https://github.com/cncf/sandbox/issues/new?assignees=&labels=New&projects=&template=application.yml&title=%5BSandbox%5D+%3CProject+Name%3E?assignees=&labels=New&projects=&template=application.yml&title=%5BSandbox%5D+%3CProject+Name%3E

Incubation is here: (TBD)

We should familiarize ourselves with it and begin preparing & collecting data to fil in each field.

SANDBOX
CNCF TOC provided guidance as to how they will review Sandbox applications.
See it here: https://github.com/cncf/sandbox#how-applications-are-reviewed

The current CNCF Sandbox Application GitHub Project Board is here: https://github.com/orgs/cncf/projects/14

As of today, there are 54 projects in the queue. I have started doing some analysis on them.

11 projects are currently in HOLD status

These projects have been given explicit feedback by TOC as to why they have not been APPROVED

- 5 have been postponed and asked to reapply in 6 ~ 12 months
- 5 have been DECLINED and REJECTED
- 1 has been advised to MERGE with a CNCF project and become a sub-project of the parent
- The above 11 project experienced an average waiting time of 4 months from making the application to getting an Decision

25 new Projects (separate to the ones on HOLD) have passed through the entire process in 2023 / 2024

- 18 have been voted on an APPROVED
- 6 have been DECLINED and/or REJECTED

**Comment by orville-wright** [comment]
Maintainers decided that we will apply into the SANDBOX level.

**Comment by orville-wright** [comment]
We received advise from Chris A (CNCF) that we are permitted to re-apply as Incubation level. 
We are now considering this option.

**Comment by edrob999** [comment]
Maintainers are still to decide, moving target date to end of this week

**Comment by orville-wright** [comment]
Decision to apply for ``` SANDBOX ``` was made on 27 May 2024.
``` SANDBOX``` Application was submitted by @edrob999  on 13 June 2024.
- CNCF Tracking Issue is here:  https://github.com/cncf/sandbox/issues/104

Great job everyone !
