### ISSUE TITLE
Activate new governance procedures for openEBS org

### ISSUE THREAD

**Issue by edrob999** [openebs/community#25]
Turn on governance procedures (after two week comment period)

**Comment by orville-wright** [comment]
The initial phase of the work has been completed.
@edrob999 has authored all new governance docs and @orville-wright  (Dave Brace) has reviewed them.
The new docs have been uploaded for review into the [openebs community](/openebs/community) repo and are live there now for all to see.

- I believe that @avishnu and @tiagolobocastro have yet to complete their reviews of the now love docs.

Once they have been reviewed, the original (outdated pre-v4.0 Unified Org docs) can be physically deleted from the [OpenEBS Parent Org](/openebs/openebs) and the **MASTER copies** will be the approved ones in the [OpenEBS Community](/openebs/community) repo. 
- After that, we need to scan the entire org for any residual copies and the old docs and delete them.

**Comment by orville-wright** [comment]
All other Maintainers have reviewed all new governance docs and have approved them. 
This item is complete.
