### ISSUE TITLE
Announce change in governance procedures for OpenEBS org

### ISSUE THREAD

**Issue by edrob999** [openebs/community#26]
When project team made decision to re-apply to CNCF, we recognized we needed to archive a number of repos, plus revise the project governance for the project. We "turned off" the existing governance procedures, to make these changes.

**Comment by orville-wright** [comment]
@edrob999  This deliverable is moving towards becoming STALE. - This needs an update or action please.

**Comment by edrob999** [comment]
Complete 🏁
