### ISSUE TITLE
Create SLACK project announcement

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#3]
Author an public announcement that is similar to the main GitHub product restructuring announcement but is targeted top post on Slack. The wording should be simplified and refined with less details. Slack has 1500+ active daily users, and  get far more daily exposure so we need to be sensitive with the wording.

Once Reviewed and approved, **Publish announcement on SLACK.**

**Comment by dave-brace** [comment]
Announcement doc and language was completed on  25 May 2024.

**Comment by dave-brace** [comment]
Announcement doc was reviewed and approved by Maintainers on 27 Mar 2024.

**Comment by dave-brace** [comment]
Announcement was published on SLACK on  Tuesday 2 April 2024
- by Dave Brace. (slack userid:  david.brace@perifery.com)
- at 10:25am

**Comment by dave-brace** [comment]
I have also created a new PROJECT STRUCTURE Overview Image in the main ORG Homepage to visually reinforce the Deprecation/Archive announcement by showing the words "Deprecated" in RED against all LEGACY Data-Engines.
