### ISSUE TITLE
Create Data Migration recommendation for Archived projects

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#4]
We need to provide Data Migration guidance and support to all community users of all OpenEBS sub-projects that are going to be Archived, EOL & made Read-Only.

We need a table that lists...

- All EOL/Archive Projects by name and repo destination
- Makes a 1 or 2 recommendations
- Provides links to the recommendation project
- Declares how many users will be affected by this action
- In some (hopefully many) cases we will recommend that users migrate to the new OpenEBS Standard (either Replicated or Non-Replicated Data-Engine).

In some cases we will be recommending users migrate to a known CNCF project.
We should calculate how many users (for each recommended project) we are sending their way, and advice those projects. As well as make a PSA announcement on Issue #1051 and Issue #3701 that a cohort of affected OpenEBS new users may be heading in that project's direction.

**Comment by orville-wright** [comment]
We need to provide migration guidance and support to all community users of all OpenEBS sub-projects that are going to be Archived, EOL & made Read-Only.

We need a table that lists...

- All EOL/Archive Projects by name and repo destination
- Makes a 1 or 2 recommendations
- Provides links to the recommendation project
- Declares how many users will be affected by this action
- In some (hopefully many) cases we will recommend that users migrate to the new OpenEBS Standard (either Replicated or Non-Replicated Data-Engine).

In some cases we will be recommending users migrate to a known CNCF project.
We should calculate how many users (for each recommended project) we are sending their way, and advice those projects. As well as make a PSA announcement on Issue #1051 and Issue #3701 that a cohort of affected OpenEBS new users may be heading in that project's direction.

**Comment by avishnu** [comment]
OpenEBS v4.0.0 provides 2 techniques for migration: using pv-migrate and using Velero, They are documented [here](https://openebs.io/docs/user-guides/data-migration/migration-overview).

**Comment by avishnu** [comment]
Using the above techniques, users of the legacy OpenEBS projects will be able to migrate to the latest OpenEBS.
