### ISSUE TITLE
Remove/change documentation files in openebs/openebs repo

### ISSUE THREAD

**Issue by edrob999** [openebs/community#40]
OpenEBS has centralized project files + policies to openebs/community. 
1. Plz remove these files from OpenEBS/OpenEBS (since they are now in community)
ADOPTERS.MD

2. Plz change GOVERNANCE.md to read:
For Governance, see [OpenEBS Umbrella Governance](https://github.com/openebs/community/blob/GOVERNANCE.md)

3. Plz change CODE_OF_CONDUCT.md to read:
For code of conduct, see [OpenEBS Umbrella Code of Conduct](https://github.com/openebs/community/blob/CODE_OF_CONDUCT.md)

4. Plz change CONTRIBUTING.md to read:
To learn about contributing to this repo, see the [OpenEBS Umbrella Contributor's Guide](https://github.com/openebs/community/blob/CONTRIBUTING.md)

**Comment by avishnu** [comment]
Completed during the course of working on https://github.com/openebs/community/issues/29
