### ISSUE TITLE
Vote to add Special Maintainers for openEBS

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#47]
## MAINTAINERS file change vote :bangbang:

This vote proposes adding 2 new Special Maintainers to the openEBS project.

These candidates are the existing maintainers within the openEBS project's. [```Local PV RAWFile```](https://github.com/openebs/rawfile-localpv) sub-project and ```OpenEBS parent project```.

| Vote ID #  | Candidate name | GitHub user ID | Company | Notes |
| :--- |  :--- |  :--- |  :---|  :--- |
| 1. | Mehran Kholdi | @semekh | Hamravesh IT | Original creator & Maintainer of RAWfile |
| 2. | Kiran Mova | @kmova | VMware | Maintainer of RAWfile, Original maintainer of openEBS |

<BR>

> [!Note]
> - The [```Local PV RAWFile```](https://github.com/openebs/rawfile-localpv) openEBS component is commonly referred to as its shortened original form...  [*RAWFile*](https://github.com/openebs/rawfile-localpv)
> -  [RAWFile](https://github.com/openebs/rawfile-localpv) was a key component of the **original openEBS parent project** prior to the CNCF assisted project restructuring initiative that began on 2 Feb 2024.
> - The openEBS Maintainers chose to retain [RAWFile](https://github.com/openebs/rawfile-localpv) and not migrate it out to the [OpenEBS Archive org](https://github.com/openebs-archive).
<BR>

1. RAWfile is officially classified by the CNCF project rules as a ```sub-project``` within the openEBS project.
3. RAWfile was conceived, designed and is maintained by a community that operates independently and in concert with the openEBS community.
4. openEBS and RAWfile co-exist in a symbiotic project/product engineering relationship for the benefit of both projects.
5. As a sub-project within openEBS, RAWfile cannot exist (by-itself) as an independent member of CNCF, or a CNCF certified project (by itself). RAWfile's membership and status in CNCF and within the CNCF Landscape is inherited from openEBS.
6. RAWfile is very complimentary to openEBS and is designed to ```integrate tightly with openEBS```. RAWfile provides additional value to openEBS, to the community, to openEBS users and to CNCF.
7. The current maintainers (at the time that we began the CNCF assisted project restructuring initiative (started on 2 Feb 2024) are:
   - [Mehran Kholdi](https://github.com/semekh)
   - [Kiran Mova](https://github.com/kmova)

## Proposal for vote (RAWfile): 
- It is proposed that @kmova and @semekh be added to new openEBS MAINTAINERS file as ```SPECIAL MAINTAINERS```
 - In their capacity as ```SPECIAL MAINTAINERS``` they will have  **```FULL authority```** to manage the RAWfile project as ```MAINTAINERS```
 - Their MAINTAINER status of the ```RAWfile project``` shall be unchanged and EQUAL to what it was **```prior```** to the CNCF assisted project restructuring initiative (started on 2 Feb 2024) 
 - Both maintainers will have  **```FULL authority```** to Raise and approve PR's against certain repos (as agreed by the openEBS MAINTAINERS)
 - While existing as a ```sub-project``` with the openEBS parent project; the RAWfile project does not maintain its own separate individual MAINTAINERS file. This is in accordance with the new openEBS structural changes as per **CNCF project guidelines**.

Note: Since the openEBS project status is Archive, this vote is governed by the new openEBS governance structure (not the Legacy Sandbox governance structure that is no longer is valid). 

## Vote :bangbang:
> [!Important]
> 1. The openEBS community is requested to comment and vote on this proposal for change to existing [MAINTAINERS](https://github.com/openebs/community/blob/develop/MAINTAINERS) file.
> 2. Current openEBS [MAINTAINERS](https://github.com/openebs/community/blob/develop/MAINTAINERS) please cast your binding votes by 15 May 2024. 
<BR>

**Comment by orville-wright** [comment]
FYI... GitHub emoji reactions are not considered binding votes. They are comment reactions only.

**Comment by avishnu** [comment]
With no disrespect to the proposed maintainers, my vote is a NO for the following reasons:

1. Rawfile localpv exists as an independent entity today, and not as a part of the OpenEBS umbrella project.
2. There's currently no adoption stats available for this project.
3. Implemented in Python, as compared to the rest of OpenEBS engines, which are either in Golang or Rust.
4. Testing strategy is not evolved.

**Comment by orville-wright** [comment]
+1 for Mehran Kholdi - (binding)
+1 for Kiran Mova - (binding)

**Comment by orville-wright** [comment]
To be clear @avishnu - this vote is only a vote on adding the current 2 RAWFile maintainers into the new openEBS MAINTAINERS file as Special Maintainers.  Your comments are directly related to the project and not the candidate people.
- We are not voting on the projects status
- We are not voting on whether the RAWfile project remains inside the openEBS project. 
- That is not what is being voted on.

**Comment by tiagolobocastro** [comment]
+1 Makes sense for Mehran to be a special maintainer for the rawfile
-1 Not sure if Kiran would want to be  - unless he himself states otherwise

**Comment by orville-wright** [comment]
> +1 Makes sense for Mehran to be a special maintainer for the rawfile
> 
> -1 Not sure if Kiran would want to be  - unless he himself states otherwise

@kmova is a current maintainer of Rawfile. Since our new Governance laws only allow 1 global instance of a Maintainers file, we must merge the Rawfile maintainers file with the new openebs maintainers file. During that merge, we cannot drop Kiran, and cannot make unilateral changes to the state of Rawfile.
Kiran would have to submit a separate request to @semekh for removal. (& the change would need to be discussed by openebs Maintainers). 
We cannot make that decision for Kiran as part of the move. Technically, this makes the vote... All or Nothing.

**Comment by avishnu** [comment]
My vote is
-1 for Mehran
-1 for Kiran
Apologies to @kmova and @semekh, as I'd like to stick to my stance that rawfile-localpv in its current stature does not qualify to be a part of OpenEBS. It could exist in https://github.com/openebs-archive, but not in https://github.com/openebs.

**Comment by avishnu** [comment]
> To be clear @avishnu - this vote is only a vote on adding the current 2 RAWFile maintainers into the new openEBS MAINTAINERS file as Special Maintainers. Your comments are directly related to the project and not the candidate people.
> 
>     * We are not voting on the projects status
> 
>     * We are not voting on whether the RAWfile project remains inside the openEBS project.
> 
>     * That is not what is being voted on.

@orville-wright I'm just stating the reasons why I down-voted.

**Comment by orville-wright** [comment]
In our due-diligence process surrounding this vote, we've discovered a number of questions that need answering.
We're not able to complete this vote yet... so this vote is postposed indefinitely until the issues are resolved..

@tiagolobocastro and @orville-wright met with Jorge Castro to get CNCF guidance on the question of... 

- "Can the Maintainers of an Org invite an external project to join a CNCF Member project ?" 
- this is the situation for RawFile and how it joined the openEBS org/project. 

Jorge Castro clarified that **YES they can**... as long as the org has **"a clear documented governance process"** to manage this situation.  - Jorge's  guidance helped significantly.
Currently, our new Governance doc does not contain this language. It  needs to be modified. So we cannot proceed with this vote.

After the governance doc is updated, we will continue this vote, but not before resolving the other outstanding issues...
1. Maintainers Vote on...
    - does the openEBS ORG (i.e. CNCF) believe that **ownership** of the **RawFile project**  & its **Intellectual Property** & its **Brand** is held by CNCF and openEBS ?
3. is RawFile a good fit for the openEBS project
4. Vote on Rawfile staying in the openEBS org
    - Yes : see item  _#4 _#5, _#5, _#7
    - No : Consensus on options of what to do (Archive, Migration, offer to Fork-out by Special Maintainer Mehran, offer to community etc)
6. Consensus on what is the criteria for RawFile to **remain** in the openEBS project
    -  (governance, conduct, engagement, technical/code, docs, responsiveness, roadmap, commits) 
8. Consensus on whether we refer to it as a **Sub-Project** or a **core Storage Engine** and why
9. Consensus on do we need a Special Maintainer for it... if its considered a **sub-project** (core storage engines do not current have Special Maintainers assigned)
10. Consensus on informing Mehran of the decision., vote, strategy  etc.

After this point, the ISSUE proposal to  **Voet to add Special Maintainer*** ... may or may not be required to continue.
@niladrih  and @Abhinandan-Purkait  votes are outstanding. Existing votes may be recast if the Maintainer wants to.

- We apologize to our community for the associated complexity... but we are implementing a new **Project Governance model** and we are learning how to better honor & respect the GNCF principles of diligent project governance.

**Comment by orville-wright** [comment]
After deeper investigation, this issue is being closed out and is being merged with the new ISSUE #49 that will continue to work and resolve all questions and issues regarding the openEBS Rawfile component.

**Comment by orville-wright** [comment]
Closed
