### ISSUE TITLE
Governance for non-project maintainers

### ISSUE THREAD

**Issue by avishnu** [openebs/community#62]
Set up governance for the following:

1. Classification of non-project maintainer categories. For eg. a sub-project maintainer, a director, a special maintainer, etc.
2. Guidelines for addition and removal of non-project maintainers.

**Comment by orville-wright** [comment]
@edrob999 advises we should not use role names that do not overlap with Corporate Titles, as they will be confusing.
(e.g. Director, Manager, Program Manager)

We have agreed to the proposal of 2 core categories...
1. Maintainers
2. Special Maintainers
- sub categories named
    - Sub-Project Maintainer  (e.g. Mehran)
    - CNCF Liaison
    - Community Manager
    - Triage Maintainer

Should we re-add an Emeritus Maintainers list ?
- This is just a ``` Badge of Honor ```
- Holds not authority and infers not rights
- We could do this as an HONOR ROLE page

``` VOTE: ``` We need to vote on final list when @tiagolobocastro returns from vacation.

**Comment by avishnu** [comment]
Completed via PR #74 and PR #78
