### ISSUE TITLE
Proposal to archive the data-populator repository

### ISSUE THREAD

**Issue by avishnu** [openebs/community#63]
The current data-populator repository (https://github.com/openebs/data-populator) has not been active since a long time. Similar functionality are now provided by other active third-party projects (eg. https://github.com/utkuozdemir/pv-migrate).

This issue is to propose an archival vote for this project and transfer the repository to [openebs-archive](https://github.com/openebs-archive) org.

**Comment by orville-wright** [comment]
Vote: 
- VA : ``` YES ```
- NH : ``` YES ```
- AP : ``` YES ```
- TC : ``` YES ```  (vote passed on by Vishnu as he's on vacation)
- DB : ``` YES ```
- ER : n/a

**Comment by avishnu** [comment]
The repo has been transferred to the https://github.com/openebs-archive organization.
