### ISSUE TITLE
Revisit issue enablement for the repositories

### ISSUE THREAD

**Issue by avishnu** [openebs/community#65]
Need to revisit all the repositories which allow for issue creation and disable if not needed or deemed to combine with other repo issues.

**Comment by orville-wright** [comment]
We should AUDIT all repo's and figure out which ones have ISSUE creation enabled.

Then we should rationalize the list down to the smallest number

We need to do a project wide announcement (and SLACK) defining...
1. How we want users & community to ``` self-manage ``` ISSUES ```  - (already done in /community/CONTRIBUTING.md)
2. What repos have ISSUES enabled

**Comment by tiagolobocastro** [comment]
Decided not to proceed with this approach.
