### ISSUE TITLE
Update project roadmap

### ISSUE THREAD

**Issue by avishnu** [openebs/community#67]
Review and update the project roadmap with features for both replicated and local engines.

**Comment by orville-wright** [comment]
Dave and Vishnu will start this work

Roadmap is not more complex than pre-Archive status...
- takes into account LocalPV + Replicated PV
- Users + contributors
- External contributors

**Comment by avishnu** [comment]
The roadmap (https://github.com/openebs/openebs/blob/main/ROADMAP.md) has been updated to reflect the true scope of the project. It's been decided to convert this into a project board for better visibility. This issue will be marked as completed once the conversions happens soon.

**Comment by avishnu** [comment]
https://github.com/openebs/openebs/pull/3779 attempts to address the notion that the Roadmap only include Mayastor items and not the Local PV.

**Comment by avishnu** [comment]
> The roadmap (https://github.com/openebs/openebs/blob/main/ROADMAP.md) has been updated to reflect the true scope of the project. It's been decided to convert this into a project board for better visibility. This issue will be marked as completed once the conversions happens soon.

The roadmap has been adequately updated taking into account feature-set for all engines of OpenEBS with this PR: https://github.com/openebs/openebs/pull/3781
Conversion into project format will be taken up in due course. Closing this as completed.
