### ISSUE TITLE
Community contributors meet

### ISSUE THREAD

**Issue by avishnu** [openebs/community#68]
Set up and establish cadence for meeting with community users and contributors.

**Comment by orville-wright** [comment]
Issues with what GMail account:  open3bs@gmail.com
We need to ensure that resources are setup for ```FIRST new``` community meeting

**Comment by avishnu** [comment]
OpenEBS holds a monthly community meeting via Zoom on the last Thursday of every month, at 14:00 hrs UTC.
Meeting Link: https://us05web.zoom.us/j/87535654586?pwd=CigbXigJPn38USc6Vuzt7qSVFoO79X.1
Meeting recordings are hosted on YouTube: https://www.youtube.com/@openebscommunity6021
