### ISSUE TITLE
Design NEW OSS Repo structure 4 Unified Data-Engines

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#7]
Design the structure of the new  OpenEBS OSS project that contains 4 Data-Engines in 1 product.

- LocalPV-Hostpath
- LocalPV-LVM
- LocalPV-ZFS
- Mayastor

Take into account the Helm installation process and user experience for net-new installs as well as migrations from old versions and upgrades..

**Comment by dave-brace** [comment]
Outstanding decisions for @avishnu 
1. What are we doing with Rawfile-LocalPV repo ?
   - @orville-wright  and @tiagolobocastro believe that it has great value and should be included in the new OpenEBS OSS repo
2. How do be prove that this work is complete ? 
   - do we have a document or visual diagram of some kind that we can attach to comments here?

**Comment by avishnu** [comment]
With the release 4.0.0, OpenEBS now has a simplified and unified installer for installing the local (Local PV Hostpath, Local PV LVM, Local PV ZFS) and replicated storage (Replicated PV Mayastor).
Refer the [documentation](https://openebs.io/docs/quickstart-guide/installation).
