### ISSUE TITLE
Commercial Support on openebs.io

### ISSUE THREAD

**Issue by edrob999** [openebs/community#76]
We have a channel on openebs.io for "Commercial Support". I'm checking with the three companies listed:
CodeWave
Cloudssky
DataCore

whether they do offer commercial support. It is reasonable to expect that each company, does offer the service, and has (or will have) a dedicated landing page for the support option.

I will update this issue with the responses received in one week (5 August). I'll update this issue with the responses received, and If we make any changes - one week for community input

**Comment by edrob999** [comment]
We also open for any other companies/individuals to be listed on the website

**Comment by orville-wright** [comment]
Seems like something we should review in the next Maintainers meeting.

**Comment by edrob999** [comment]
As discussed in the maintainers meeting [September 13](https://github.com/openebs/community/discussions/88) the companies Codewave, Cloudssky have not been responsive to requests for commercial support.

The maintainers voted to remove the two companies from the commercial support section of the website. 
We also gave the community an update on the issue in the community meeting Oct 31.  Extending this issue for another three weeks to be decided on Wednesday Nov 20th, during the maintainers meeting.

For full disclosure: If these two companies are removed from openebs.com commercial support, the only remaining company listed as providing support will be DataCore (my employer). 
Any companies/individuals that do want to be listed, can add a comment to this issue (and the maintainers will contact you)

**Comment by edrob999** [comment]
My engagement with the project is now concluded, assigning to @avishnu

**Comment by avishnu** [comment]
@balaharish7 Can you please take a look at this?

**Comment by balaharish7** [comment]
Sure! @avishnu

**Comment by balaharish7** [comment]
This issue is resolved in the [PR #505](https://github.com/openebs/website/pull/505). This issue can be closed. @avishnu
