### ISSUE TITLE
Update/Modernize the Tech Docs website

### ISSUE THREAD

**Issue by orville-wright** [openebs/community#9]

**Comment by avishnu** [comment]
Currently, it's been decided:
1. Most of the blogs are outdated, need to disable the entire blogs section till further auditing
2. Check the contents and update them wherever applicable
3. Check the links and fix them wherever applicable (404 errors)

**Comment by avishnu** [comment]
> Currently, it's been decided:
> 
>     1. Most of the blogs are outdated, need to disable the entire blogs section till further auditing
> 
>     2. Check the contents and update them wherever applicable
> 
>     3. Check the links and fix them wherever applicable (404 errors)

Above are completed.
