### ISSUE TITLE
Modifications to Sandbox application submission

### ISSUE THREAD

**Issue by avishnu** [openebs/community#92]
OpenEBS has re-applied to CNCF Sandbox with this application https://github.com/cncf/sandbox/issues/104

Parts of the application need corrections based on feedback received informally. This issue is for tracking the changes that are being proposed.

**Comment by avishnu** [comment]
The modified application draft is as follows:


Application contact emails
ed.robinson@gmail.com, brace.dave@gmail.com, tiagolobocastro@gmail.com,
vishnu.attur@gmail.com
Also see OpenEBS project leadership Maintainers team
Project Summary
Cloud native storage
Project Description
OpenEBS was accepted as a Sandbox project in 2019, then moved to archive in Feb 2024.
For background on why, see OpenEBS - why we were archived. The project team and
sponsoring company have made changes in order to ensure the long term sustainability of
OpenEBS. We are asking to unarchive the project, and are challenging ourselves to move
forward in the CNCF maturity process.
OpenEBS provides enterprise grade block storage for Kubernetes, enabling persistent
resilient cloud native storage (storage is managed-from and contained-within a Kubernetes
cluster). OpenEBS is popular, with >25,000 new clusters installed every month.
This is a re-application to Sandbox. Project was archived Feb 2024 after TOC vote on 1051.
The team has listened to TOC feedback, has made changes, and is now seeking
readmission to Sandbox.
Changes include:
• Archived older storage engines and consolidated engines from 11 to 4 (75 repos to
38), these are the actively maintained repos that will be further developed in the
future.
• Reworked documentation
• Reworked all governance docs, and centralized to umbrella Community repo
• Rewrote project docs including Vision.md, Governance.md, Contributing.md
• Instituted processes inside the project, so people abide by the project docs
• Engaged with Linux Foundation brand counsel (DanielC) to bring DataCore’s
commercial offering into compliance
• Project members attended KubeCon Paris, in order to engage with the community
on how best to proceed reapplying for sandbox in the most efficient manner
possible - the OpenEBS team has been working with the CNCF Projects team to
help meeting the requirements. (ChrisA and JorgeC)
• Educated the sponsoring organisation on open source and CNCF policies and
procedures
• Assigned a CNCF liaison (Ed Robinson), to represent the project and take guidance
from the TOC
The team hopes to gain admission to Sandbox soon, then work with CNCF towards
incubation, then graduation.
Org repo URL (provide if all repos under the org are in scope of the application)
https://github.com/openebs
Project repo URL in scope of application
https://github.com/openebs/openebs
Additional repos in scope of the application
The new OpenEBS project consists of 5 Storage Engines. The strategy is to eventually unify
all 5 into 1 platform. There are sub repos & dependencies, 1 sub project & 1 critical
external fork dependency. The Team took advice from TOC, and advised community, then
deprecated, then moved tech-debt of 44 legacy repos to openebs-archive org based on
guidance from @caniszczyk and @castrojo. - The new repo structure is listed below, with
engines listed in order of User Adoption:
Name Project Repos
Community https://github.com/openebs/community/
Local PV Hostpath https://github.com/openebs/dynamic-localpv-
provisioner
Local PV ZFS https://github.com/openebs/zfs-localpv
Local PV LVM https://github.com/openebs/lvm-localpv
Replicated PV Mayastor https://github.com/openebs/mayastor
https://github.com/openebs/mayastor-control-plane
https://github.com/openebs/mayastor-extensions
https://github.com/openebs/spdk-rs
SPDK fork w/OpenEBS
patches https://github.com/openebs/spdk
Local PV Raw Device https://github.com/openebs/rawfile-localpv
Note: SPDK patches are available to the community
Website URL
https://openebs.io
https://openebs.io/docs
Roadmap
https://github.com/openebs/openebs/blob/main/ROADMAP.md
Roadmap context
The new project roadmap & strategy is to eventually unify 5 Storage Engines into 1 single
Storage platform. This is a major project change compared to the old roadmap, which did
not provide enough attention and focus on the 4 Local PV engines. The team acknowledges
this lack of focus which created a stale & disappointed community with low contributions.
The Team has defined a VISION doc as part of the new GOVERNANCE structure that
supports the roadmap and helps guide the Team, the contributors and the community.
The new Roadmap + VISION doc defines a commitment to all 5 Storage Engines and the
entire user community.
Contributing Guide
https://github.com/openebs/community/blob/develop/CONTRIBUTING.md
Code of Conduct (CoC)
https://github.com/openebs/community/blob/develop/CODE_OF_CONDUCT.md
Adopters
https://github.com/openebs/community/blob/develop/ADOPTERS.md
Contributing or Sponsoring Org
https://www.datacore.com/
Maintainers file
https://github.com/openebs/community/blob/develop/MAINTAINERS
IP Policy
If the project is accepted, I agree the project will follow the CNCF IP Policy
Trademark and accounts
If the project is accepted, I agree to donate all project trademarks and accounts to the
CNCF
Why CNCF?
OpenEBS was accepted as a Sandbox project in 2019, then moved to archive in Feb 2024.
The Team has re-examined why we want to continue to contribute to CNCF. Here is why:
• CNCF as an organization is able to protect, guide and nurture the Kubernetes open
source platform.
• Under CNCF’s guidance & governance OpenEBS aims to democratize persistent
storage for K8s for a wide range of use cases.
• Aligning with CNCF’s mission, OpenEBS can leverage CNCF’s community and
guidance to drive innovation, adoption, and growth.
• Thousands of clusters trust OpenEBS to reliably manage persistent data in K8s.
• The Team is proud of the progress, and being able to work with cloud-native
adopters, together we are innovating and enabling the community for the future.
Benefit to the Landscape
Key benefits of OpenEBS are:
• Resilient and reliable data management capabilities within Kubernetes
• Software-defined, container-native and device agnostic
• Seamless migration capabilities of legacy deployments to Kubernetes
Cloud Native 'Fit'
OpenEBS is cloud native storage which enables K8s stateful apps with persistent block
storage.
Cloud Native 'Integration'
Kubernetes
Containerd
KubeVirt
Kubernetes
Etcd
NATS
HELM
gRPC
Jaeger
OpenTelemetry
Prometheus
Open Telemetry
Cloud Native Overlap
Longhorn (storage)
CubeFS (storage)
Rook/Ceph (storage)
Similar projects
Longhorn (storage)
CubeFS (storage)
Rook/Ceph (storage)
Landscape
Cloud Native Storage
Business Product or Service to Project separation
The sponsoring company, DataCore offers premium support services to OpenEBS
adopters and production users.
The company plans to release a future offering to provide enhanced enterprise
management solutions complementing OpenEBS.
The prior commercial offering “openEBS Pro” had trademark issues with Linux Foundation
and has been withdrawn.
Project presentations
Prior to project-archiving, OpenEBS has participated with TAG Storage. The Team met once
with TAG Storage post archiving in July 2024.
Project champions
Jorge Castro
Chris Aniszczyk
Emily Fox
Nick Connolly
Alex Chircop
Additional information
OpenEBS production installations
• Microsoft uses OpenEBS in Azure Container services
• CIVO uses OpenEBS as the basis for their CSP offerings
• Flipkart, India’s largest eCommerce service has relied on OpenEBS for their storage
• Replicated's Embedded Cluster and kURL products use OpenEBS as the default
storage provider.
• … and more
The Team has accepted the feedback and adopted changes recommended by the TOC in
February 2024.
While OpenEBS is in Archive, the users are uncertain of the project’s future, and the future
of their own software that depends on OpenEBS.
We request TOC to consider OpenEBS for a promotion to Sandbox, the Team commits to
work with CNCF guidance to develop and execute a plan to move the project to its next
level.

**Comment by avishnu** [comment]
[Sandbox submission - edit v1.pdf](https://github.com/user-attachments/files/17174602/Sandbox.submission.-.edit.v1.pdf)
The proposed changes are in the pdf (edit.v1)

**Comment by avishnu** [comment]
[Sandbox submission - edit v2.pdf](https://github.com/user-attachments/files/17174624/Sandbox.submission.-.edit.v2.pdf)
Feedback from @Abhinandan-Purkait and @niladrih have been considered in the pdf (edit.v2)

**Comment by tiagolobocastro** [comment]
edits looks good to me too

**Comment by Abhinandan-Purkait** [comment]
Edit looks good to me.

`Business Product or Service to Project separation
The sponsoring company, DataCore offers premium support services to OpenEBS
adopters and production users`

I think we should replace premium support with enterprise support.

Flipkart, India'  s  --> Flipkart, India's

Thanks

**Comment by niladrih** [comment]
LGTM

**Comment by avishnu** [comment]
> Flipkart, India' s --> Flipkart, India's

Fixed this in v3. Attached here.
[Sandbox submission - edit v3.pdf](https://github.com/user-attachments/files/17175682/Sandbox.submission.-.edit.v3.pdf)

**Comment by orville-wright** [comment]
LGTM - approved.

**Comment by avishnu** [comment]
Thanks to all maintainers for their approvals.

**Comment by tiagolobocastro** [comment]
I think this can now be closed?
